version: "3.8"
services:
  react-gpt3:
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GPT3_KEY=${REACT_APP_GPT3_KEY}
